import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not found.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const BASE_PROMPT = `
Enhance this photo to a professional, studio-level quality. Apply advanced lighting correction to create a dramatic yet natural feel. Improve contrast and sharpness to make details pop. 
Perform subtle skin smoothing while meticulously preserving natural texture. Refine the background to remove distracting elements and add a slight, pleasing depth of field. 
Apply sophisticated color grading for a polished, portfolio-ready look. The final image should be realistic and highly detailed, suitable for a magazine cover or a professional portrait portfolio.
`;

const PREVIEW_PROMPT_MODIFIER = `
Generate a fast, low-resolution preview of the enhancement. Prioritize speed over final quality. The general style and adjustments should be visible, but fine details are not necessary for this preview.
`;

const callGeminiImageAPI = async (base64ImageData: string, mimeType: string, prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    { inlineData: { data: base64ImageData, mimeType: mimeType } },
                    { text: prompt },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
                return part.inlineData.data;
            }
        }
        throw new Error('No image was generated by the API.');
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("The AI model failed to process the image. Please try again.");
    }
};

const buildPromptWithContrast = (basePrompt: string, contrast?: number): string => {
    let finalPrompt = basePrompt;
    if (contrast !== undefined) {
      let contrastDescription = 'normal';
      if (contrast < 20) contrastDescription = 'very low';
      else if (contrast < 40) contrastDescription = 'low';
      else if (contrast > 60) contrastDescription = 'high';
      else if (contrast > 80) contrastDescription = 'very high';
      
      if (contrastDescription !== 'normal') {
          finalPrompt += `\nPay special attention to setting a ${contrastDescription} contrast.`;
      }
    }
    return finalPrompt;
};

export const generatePreview = async (base64ImageData: string, mimeType: string, contrast?: number): Promise<string> => {
    const prompt = buildPromptWithContrast(PREVIEW_PROMPT_MODIFIER + BASE_PROMPT, contrast);
    return callGeminiImageAPI(base64ImageData, mimeType, prompt);
};

export const enhancePhoto = async (base64ImageData: string, mimeType: string, contrast?: number): Promise<string> => {
    const prompt = buildPromptWithContrast(BASE_PROMPT, contrast);
    return callGeminiImageAPI(base64ImageData, mimeType, prompt);
};