
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not found.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const PROMPT = `
Enhance this photo to a professional, studio-level quality. Apply advanced lighting correction to create a dramatic yet natural feel. Improve contrast and sharpness to make details pop. 
Perform subtle skin smoothing while meticulously preserving natural texture. Refine the background to remove distracting elements and add a slight, pleasing depth of field. 
Apply sophisticated color grading for a polished, portfolio-ready look. The final image should be realistic and highly detailed, suitable for a magazine cover or a professional portrait portfolio.
`;

export const enhancePhoto = async (base64ImageData: string, mimeType: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: PROMPT,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("The AI model failed to process the image. Please try again.");
  }
};
