
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not found.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const getIntensityDescription = (intensity: number): string => {
  if (intensity <= 25) {
    return "Apply very subtle and minor adjustments. The changes should be barely noticeable, focusing only on the most essential corrections.";
  }
  if (intensity <= 50) {
    return "Apply subtle enhancements. Focus on a natural look, gently improving lighting and clarity without drastic changes.";
  }
  if (intensity <= 75) {
    return "Apply moderate and noticeable enhancements. The goal is a clearly improved but still realistic photo.";
  }
  return "Apply strong and dramatic, portfolio-ready enhancements. Be bold with lighting, color, and contrast to create a stunning, professional image.";
}

const createPrompt = (intensity: number): string => {
    const intensityDescription = getIntensityDescription(intensity);
    return `
Enhance this photo to a professional, studio-level quality. 
Intensity instruction: ${intensityDescription}

Apply the following techniques based on the intensity instruction:
- Advanced lighting correction to create a dramatic yet natural feel.
- Improve contrast and sharpness to make details pop.
- Perform subtle skin smoothing while meticulously preserving natural texture.
- Refine the background to remove distracting elements and add a slight, pleasing depth of field.
- Apply sophisticated color grading for a polished look.

The final image should be realistic and highly detailed, suitable for a magazine cover or a professional portrait portfolio, with the specified intensity.
`;
}

export const enhancePhoto = async (base64ImageData: string, mimeType: string, intensity: number): Promise<string> => {
  try {
    const prompt = createPrompt(intensity);
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("The AI model failed to process the image. Please try again.");
  }
};
